version: "3.8"

services:
  db:
    container_name: db_market
    image: postgres
    restart: always
    ports:
      - 6543:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # esearch:
  #   container_name: search
  #   image: elasticsearch:7.14.2
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9500:9200
