version: "3.8"

services:
  db:
    container_name: db_market
    image: postgres
    restart: always
    ports:
      - 6543:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # esearch:
  #   container_name: search
  #   image: elasticsearch:7.14.2
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9500:9200

  rabbitmq:
    image: rabbitmq:3-management
    ports:
     - 5672:5672
     - 15672:15672
    
  celery:
    build:
      context: .
      dockerfile: worker.Dockerfile
    command: celery -A shop_app worker -l info
    network_mode: host
    restart: always
    environment:
      rabbitmq_uri: amqp://127.0.0.1:5672
    depends_on:
     - rabbitmq

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
