# Generated by Django 4.2.3 on 2023-07-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='attribute_value',
            field=models.ManyToManyField(related_name='product_item', through='inventory.ProductItemAttribute', to='inventory.productattributevalue'),
        ),
    ]
