# Generated by Django 4.2.3 on 2023-07-31 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d/'),
        ),
    ]
