# Generated by Django 4.2.3 on 2023-08-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_productmedia_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='img_url',
            field=models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d'),
        ),
    ]
