# Generated by Django 4.2.3 on 2023-08-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_productitem_price_alter_productmedia_img_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productitem',
            options={'ordering': ['sku']},
        ),
        migrations.AddIndex(
            model_name='productitem',
            index=models.Index(fields=['sku'], name='inventory_p_sku_6ff1bc_idx'),
        ),
    ]
